# 坐标, 第一个x, 第二个y

team:
## 选择的队伍
  #0 - 500
  #1 - 1200
  #2 - 1900
  - 1900
  - 350
choose:
## 选择按钮
  - 2200
  - 1200

next_turn:
## 回合结束按钮
  - 2300
  - 700

skill_0:
  - 930
  - 700
skill_1:
  - 1250
  - 700
skill_2:
  - 1600
  - 700

# PVP
setting:
##右上角设置栏
  - 2500
  - 90
surrender:
## 投降
  - 1280
  - 300

# PVE
bonus_confirm:
## 奖励buff的获取按钮
  - 1600
  - 1300
check_team:
## 地图下方的查看队伍按钮
  - 1000
  - 1400
give_up:
## 查看队伍后的放弃按钮
  - 1500
  - 1100
global_confirm:
## 第一次选取佣兵队伍后的弹出提示确定按钮
  - 1000
  - 870
mystery_confirm:
## 选取神秘来客后的确定按钮
  - 1230
  - 1200